Organizations:

  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/property.com/orderer.property.com/orderers/orderer.property.com/msp
    
    Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    OrdererEndpoints:
            - orderer.property.com:7050
#Police --> Admin
  - &Admin
    Name: AdminMSP
    ID: AdminMSP
    MSPDir: organizations/peerOrganizations/property.com/admin.property.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('AdminMSP.admin', 'AdminMSP.peer', 'AdminMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('AdminMSP.admin', 'AdminMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('AdminMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('AdminMSP.peer')"     

    AnchorPeers:
      - Host: peer0.Admin.property.com
        Port: 7051
#Driver --> User
  - &User
    Name: UserMSP
    ID: UserMSP
    MSPDir: organizations/peerOrganizations/property.com/user.property.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('UserMSP.admin', 'UserMSP.peer', 'UserMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('UserMSP.admin', 'UserMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('UserMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('UserMSP.peer')" 

    AnchorPeers:
      - Host: peer0.User.property.com
        Port: 9051

Capabilities:

    Channel: &ChannelCapabilities

        V2_0: true


    Orderer: &OrdererCapabilities
    
        V2_0: true

    Application: &ApplicationCapabilities

        V2_0: true
# Orderer

Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: etcdraft

    Addresses:
        - orderer.property.com:7050

    EtcdRaft:
        Consenters:
        - Host: orderer.property.com
          Port: 7050
          ClientTLSCert: organizations/ordererOrganizations/property.com/orderer.property.com/orderers/orderer.property.com/tls/server.crt
          ServerTLSCert: organizations/ordererOrganizations/property.com/orderer.property.com/orderers/orderer.property.com/tls/server.crt

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
            
Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


    Capabilities:
        <<: *ChannelCapabilities
# Application

Application: &ApplicationDefaults

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
    OrdererGenesis:
      <<: *ChannelDefaults
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        AutoConsortium:
          Organizations:
            - *Admin 
            - *User

            
    AutoChannel:
      Consortium: AutoConsortium
      <<: *ChannelDefaults
      Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Admin 
            - *User
         
        Capabilities:
          <<: *ApplicationCapabilities

