#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  propertymobile:

services:
  couchdbAdminPeer0:
    container_name: couchdbAdminPeer0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer0.Admin
      - COUCHDB_PASSWORD=password
    ports:
      - 5984:5984
    networks:
      - propertymobile

  couchdbUserPeer0:
    container_name: couchdbUserPeer0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer0.User
      - COUCHDB_PASSWORD=password
    ports:
      - 7984:5984
    networks:
      - propertymobile

  couchdbMvdPeer0:
    container_name: couchdbMvdPeer0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=peer0.Mvd
      - COUCHDB_PASSWORD=password
    ports:
      - 9984:5984
    networks:
      - propertymobile

  orderer.property.com:
    container_name: orderer.property.com
    image: hyperledger/fabric-orderer:2.2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/property.com/orderer.property.com/orderers/orderer.property.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/property.com/orderer.property.com/orderers/orderer.property.com/tls:/var/hyperledger/orderer/tls
    networks:
      - propertymobile

  peer0.admin.property.com:
    container_name: peer0.admin.property.com
    image: hyperledger/fabric-peer:2.2.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.admin.property.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.admin.property.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.admin.property.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.admin.property.com:7051
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_ADDRESS=peer0.admin.property.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_propertymobile
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbAdminPeer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.Admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/property.com/admin.property.com/peers/peer0.admin.property.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/property.com/admin.property.com/peers/peer0.admin.property.com/tls:/etc/hyperledger/fabric/tls
      
    depends_on:
      - orderer.property.com
      - couchdbAdminPeer0  
    networks:
      - propertymobile

  peer0.user.property.com:
    container_name: peer0.user.property.com
    image: hyperledger/fabric-peer:2.2.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.user.property.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.user.property.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.user.property.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.user.property.com:9051
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=UserMSP
      - CORE_PEER_ADDRESS=peer0.user.property.com:9051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_propertymobile
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbUserPeer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.User
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:9051
      - 9053:9053
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/property.com/user.property.com/peers/peer0.user.property.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/property.com/user.property.com/peers/peer0.user.property.com/tls:/etc/hyperledger/fabric/tls
      
    depends_on:
      - orderer.property.com
      - couchdbUserPeer0  
    networks:
      - propertymobile 

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.3
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.admin.property.com:7051
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/property.com/admin.property.com/peers/peer0.admin.property.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/property.com/admin.property.com/peers/peer0.admin.property.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/property.com/admin.property.com/peers/peer0.admin.property.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/property.com/admin.property.com/users/Admin@admin.property.com/msp
      - ORDERER_TLS_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/property.com/orderer.property.com/msp/tlscacerts/tlsca.property.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../../Chaincode/:/opt/gopath/src/github.com/chaincode/
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/
    networks:
        - propertymobile
    depends_on:
      - orderer.property.com
      - peer0.admin.property.com
      - peer0.user.property.com

